# Code generated by SdkContractGenerator. DO NOT EDIT.

CONTRACT = {
    "audio-to-video": {
        "models": ["infinitetalk-from-audio"],
        "fields_by_model": {
            "infinitetalk-from-audio": {
                "output_resolution": {
                    "enum": ["480p", "720p"]
                },
                "seed": {
                    "type": "integer"
                },
                "source_audio_url": {
                    "required": True
                },
                "source_image_url": {
                    "required": True
                }
            }
        }
    }
}
